### ISSUE TITLE
无法正常运行

### ISSUE THREAD

**Issue by sli1989** [zhwangart/hexo-theme-acorn#1]
```
ERROR TypeError: D:\WIT\hexo\themes\acorn\layout\archive.ejs:2
    1| <div class="container">
 >> 2|   <%- partial('_partial/page/header') %>
    3|   <%- partial('_partial/archive', {pagination: config.archive, index: true}) %>
    4| </div>

D:\WIT\hexo\themes\acorn\layout\_partial\page\header.ejs:9
    7|   <h5 class="slogan font-w-lighter text-gray">
    8|     <% if (is_archive()) { %>
 >> 9|     <%- theme.banner.archives %>
    10|     <% } else if (is_page()) { %>
    11|     <%- theme.banner.pages %>
    12|     <% } else {%>

Cannot read properties of undefined (reading 'archives')
    at eval (D:\WIT\hexo\themes\acorn\layout\_partial\page\header.ejs:24:30)
    at header (D:\WIT\hexo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\WIT\hexo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (D:\WIT\hexo\themes\acorn\layout\archive.ejs:12:17)
    at archive (D:\WIT\hexo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\WIT\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\WIT\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\WIT\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\WIT\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:988:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  path: 'D:\\WIT\\hexo\\themes\\acorn\\layout\\archive.ejs'
}
ERROR TypeError: D:\WIT\hexo\themes\acorn\layout\archive.ejs:2
    1| <div class="container">
 >> 2|   <%- partial('_partial/page/header') %>
    3|   <%- partial('_partial/archive', {pagination: config.archive, index: true}) %>
    4| </div>

D:\WIT\hexo\themes\acorn\layout\_partial\page\header.ejs:9
    7|   <h5 class="slogan font-w-lighter text-gray">
    8|     <% if (is_archive()) { %>
 >> 9|     <%- theme.banner.archives %>
    10|     <% } else if (is_page()) { %>
    11|     <%- theme.banner.pages %>
    12|     <% } else {%>

Cannot read properties of undefined (reading 'archives')
    at eval (D:\WIT\hexo\themes\acorn\layout\_partial\page\header.ejs:24:30)
    at header (D:\WIT\hexo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\WIT\hexo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (D:\WIT\hexo\themes\acorn\layout\archive.ejs:12:17)
    at archive (D:\WIT\hexo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\WIT\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\WIT\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\WIT\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\WIT\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:988:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  path: 'D:\\WIT\\hexo\\themes\\acorn\\layout\\archive.ejs'
}
ERROR TypeError: D:\WIT\hexo\themes\acorn\layout\archive.ejs:2
    1| <div class="container">
 >> 2|   <%- partial('_partial/page/header') %>
    3|   <%- partial('_partial/archive', {pagination: config.archive, index: true}) %>
    4| </div>

D:\WIT\hexo\themes\acorn\layout\_partial\page\header.ejs:9
    7|   <h5 class="slogan font-w-lighter text-gray">
    8|     <% if (is_archive()) { %>
 >> 9|     <%- theme.banner.archives %>
    10|     <% } else if (is_page()) { %>
    11|     <%- theme.banner.pages %>
    12|     <% } else {%>

Cannot read properties of undefined (reading 'archives')
    at eval (D:\WIT\hexo\themes\acorn\layout\_partial\page\header.ejs:24:30)
    at header (D:\WIT\hexo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\WIT\hexo\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (D:\WIT\hexo\themes\acorn\layout\archive.ejs:12:17)
    at archive (D:\WIT\hexo\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\WIT\hexo\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\WIT\hexo\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\WIT\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at D:\WIT\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\WIT\hexo\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:988:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  path: 'D:\\WIT\\hexo\\themes\\acorn\\layout\\archive.ejs'
}

```

**Comment by zhwangart** [comment]
@sli1989 请更新一下代码，感谢及时告知，我们正在不断的完善 Acorn 主题。
