### ISSUE TITLE
Bug: plugins.ejs 渲染错误

### ISSUE THREAD

**Issue by guiqiqi** [zhwangart/hexo-theme-acorn#16]
- 错误输出：
```
Unhandled rejection TypeError: /Users/doge/Desktop/duoji/themes/acorn/layout/plugins.ejs:5
    3|   <%- partial('_partial/page/heading') %>
    4|   <div class="row flex-wrap">
 >> 5|     <% site.data[page.data].forEach(function(plugin){%>
    6|       <%- partial('_partial/' + page.partial, {plugin: plugin}) %>
    7|     <% }) %>
    8|   </div>

Cannot read properties of undefined (reading 'forEach')
    at eval ("/Users/doge/Desktop/duoji/themes/acorn/layout/plugins.ejs":15:29)
    at plugins (/Users/doge/Desktop/duoji/node_modules/ejs/lib/ejs.js:703:17)
    at _View._compiled (/Users/doge/Desktop/duoji/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/doge/Desktop/duoji/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/doge/Desktop/duoji/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/doge/Desktop/duoji/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/doge/Desktop/duoji/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/doge/Desktop/duoji/node_modules/hexo/lib/hexo/router.js:47:5)
    at Readable.read (node:internal/streams/readable:547:12)
    at resume_ (node:internal/streams/readable:1048:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
- 复现步骤：使用 `hexo init` 新建空白项目，下载最新版本 acorn 主题，并使用 acorn-sample-data 的样板数据文件，运行服务，之后单击顶部导航栏中的 “画廊” 或者 “案例”，即出现渲染错误。
- 软件版本：
  - node: 20.8.0
  - hexo: 6.3.0
  - hexo-cli: 4.3.1
  - acorn: 8.10.0
- 推测的可能原因：
  - 使用 `<%- site.data.hasOwnProperty(page.data) -%>` 在 `plugins.ejs` 中进行调试，结果输出 `false`
  - 使用 `<%- Object.keys(site.data).length -%>` 在 `plugins.ejs` 中进行调试，结果输出 `0`
  - 可能新版本的 Hexo API 移除了 `site.data` 支持？

谢谢作者的工作。

**Comment by guiqiqi** [comment]
重新配置两次之后问题无法复现了，不清楚问题出在哪里了。感谢作者的工作。
关闭 Issue。

**Comment by sli1989** [comment]
~~遇到同样问题，到底咋回事呀~~

---

检查 `_data` 数据库页面是否对应上即可。
