### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by sli1989** [zhwangart/hexo-theme-acorn#3]
遇到几个问题，大佬有空可以优化下。

- 不知道是不是我的问题。node最新版存在错误提示，好像不太影响部署。
```
ERROR TypeError: /builds/sli1989/csic/themes/acorn/layout/plugins.ejs:5
    3|   <%- partial('_partial/page/heading') %>
    4|   <div class="row flex-wrap">
 >> 5|     <% site.data[page.data].forEach(function(plugin){%>
    6|       <%- partial('_partial/' + page.partial, {plugin: plugin}) %>
    7|     <% }) %>
    8|   </div>
Cannot read properties of undefined (reading 'forEach')
    at eval (/builds/sli1989/csic/themes/acorn/layout/plugins.ejs:15:29)
    at plugins (/builds/sli1989/csic/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/builds/sli1989/csic/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/builds/sli1989/csic/node_modules/hexo/lib/theme/view.js:39:17)
    at /builds/sli1989/csic/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/builds/sli1989/csic/node_modules/bluebird/js/release/util.js:16:23)
    at /builds/sli1989/csic/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/builds/sli1989/csic/node_modules/hexo/lib/hexo/router.js:[47](https://gitlab.com/sli1989/csic/-/jobs/2158824701#L47):5)
    at RouteStream.Readable.read (node:internal/streams/readable:[48](https://gitlab.com/sli1989/csic/-/jobs/2158824701#L48)7:10)
    at resume_ (node:internal/streams/readable:988:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  path: '/builds/sli1989/csic/themes/acorn/layout/plugins.ejs'
}
```
- 如果存在站点url的子目录情况，很多图片无法直接调用url的子目录。
- post
  - 上下篇的位置需要优化，标签需要优化。
- card
  - 全局card图片大小需要优化。max width 100% 无法自适应一致。
  - 针对post的description，一行、二行的不一致排列，导致卡片无法对齐。

---

- 主题config没有使用datafile
- 正文text-align: justify 会造成主页插件标题、footer不一致。
- culture，gallery等使用grid的样式，如果调整排列网格个数，会造成非居中问题。从而导致首页的culture，gallery等涉及grid row没有居中。使用 justify-content: center 又会造成achieve排版左对齐。
- grid 的小界面设备适配性需要优化（存在单列问题）

**Comment by zhwangart** [comment]
@sli1989 

已做优化，更新一下看看～
