### ISSUE TITLE
只要把gallery\index.md放到source里面就会报错，应该怎么解决啊？

### ISSUE THREAD

**Issue by txxxtxx** [zhwangart/hexo-theme-acorn#8]
``` bash
INFO  Start processing
INFO  Files loaded in 171 ms
ERROR F:\hexo\hexo.github.io\themes\acorn\layout\plugins.ejs:6
    4|   <div class="row flex-wrap">
    5|     <% site.data[page.data].forEach(function(plugin){%>
 >> 6|       <%- partial('_partial/' + page.partial, {plugin: plugin}) %>
    7|     <% }) %>
    8|   </div>
    9| </div>

F:\hexo\hexo.github.io\themes\acorn\layout\_partial\gallery.ejs:3
    1| <div class="col-4">
    2|   <div class="card rounded">
 >> 3|     <a href="<%= url_for(plugin.link) %>">
    4|       <img class="card-img" src="<%= url_for(plugin.cover) %>" alt="<% plugin.name %>">
    5|     </a>
    6|     <div class="card-body bg-light">

Cannot read property '0' of null
TypeError: F:\hexo\hexo.github.io\themes\acorn\layout\plugins.ejs:6
    4|   <div class="row flex-wrap">
    5|     <% site.data[page.data].forEach(function(plugin){%>
 >> 6|       <%- partial('_partial/' + page.partial, {plugin: plugin}) %>
    7|     <% }) %>
    8|   </div>
    9| </div>

F:\hexo\hexo.github.io\themes\acorn\layout\_partial\gallery.ejs:3
    1| <div class="col-4">
    2|   <div class="card rounded">
 >> 3|     <a href="<%= url_for(plugin.link) %>">
    4|       <img class="card-img" src="<%= url_for(plugin.cover) %>" alt="<% plugin.name %>">
    5|     </a>
    6|     <div class="card-body bg-light">

Cannot read property '0' of null
    at Object.urlForHelper (F:\hexo\hexo.github.io\node_modules\hexo\lib\plugins\helper\url_for.js:6:11)
    at eval (F:\hexo\hexo.github.io\themes\acorn\layout\_partial\gallery.ejs:12:26)
    at gallery (F:\hexo\hexo.github.io\node_modules\ejs\lib\ejs.js:682:17)
    at Theme._View.View._compiledSync (F:\hexo\hexo.github.io\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (F:\hexo\hexo.github.io\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (F:\hexo\hexo.github.io\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (F:\hexo\hexo.github.io\themes\acorn\layout\plugins.ejs:18:17)
    at Array.forEach (<anonymous>)
    at eval (F:\hexo\hexo.github.io\themes\acorn\layout\plugins.ejs:15:29)
    at plugins (F:\hexo\hexo.github.io\node_modules\ejs\lib\ejs.js:682:17)
    at Theme._View.View._compiled (F:\hexo\hexo.github.io\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (F:\hexo\hexo.github.io\node_modules\hexo\lib\theme\view.js:30:15)
    at F:\hexo\hexo.github.io\node_modules\hexo\lib\hexo\index.js:394:29
    at tryCatcher (F:\hexo\hexo.github.io\node_modules\bluebird\js\release\util.js:16:23)
    at F:\hexo\hexo.github.io\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\hexo\hexo.github.io\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:490:10)
    at resume_ (_stream_readable.js:975:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
INFO  0 files generated in 206 ms

```

**Comment by txxxtxx** [comment]
hexo忘记升版本
